version: '3.8'

services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./api-gateway:/app/src
    command: go run main.go

  login-service:
    build:
      context: ./backend-services/login-service
      dockerfile: Dockerfile
    ports:
      - '9090:9090'
    volumes:
      - ./login-service:/app/src
    command: go run main.go

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: 12345
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '6969:6969'

volumes:
  db-data:
